/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo.obs;

import Demo.Obseverble;

/**
 *
 * @author ASUS
 */
public class Helicopter extends javax.swing.JFrame implements Observer {
     private Obseverble obs;
     
   

    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        this.setTitle("Helicopter");
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblarea = new javax.swing.JLabel();
        btnlaser = new javax.swing.JButton();
        btnmissile = new javax.swing.JButton();
        btnshoot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaH = new javax.swing.JTextArea();
        textfield1 = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        positioncheck = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblarea.setText("Area Not Cleared");
        jPanel1.add(lblarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 30));

        btnlaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlaser.setText("Laser Operation");
        btnlaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaserActionPerformed(evt);
            }
        });
        jPanel1.add(btnlaser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 40));

        btnmissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmissile.setText("Missile Operation ");
        jPanel1.add(btnmissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 40));

        btnshoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnshoot.setText("Shoot");
        jPanel1.add(btnshoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 40));

        textareaH.setColumns(20);
        textareaH.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        textareaH.setRows(5);
        jScrollPane1.setViewportView(textareaH);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 430, 150));

        textfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield1ActionPerformed(evt);
            }
        });
        jPanel1.add(textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 350, -1));

        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 70, 30));

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 370));

        positioncheck.setText("Position");
        jPanel1.add(positioncheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 100, 30));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel3.setText("Ammo Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, 20));

        jLabel4.setText("Soldier Count");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 110, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaserActionPerformed

    private void textfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield1ActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_textfield1ActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        if(obs!=null){
            String data = textfield1.getText();
            obs.DiliverMessege("Helicopter : "+data+"\n");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnsendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlaser;
    private javax.swing.JButton btnmissile;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnshoot;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblarea;
    private javax.swing.JCheckBox positioncheck;
    public javax.swing.JTextArea textareaH;
    private javax.swing.JTextField textfield1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateValue(int value) {
       if(positioncheck.isSelected()==true){
             btnshoot.setEnabled(20<value);
             btnmissile.setEnabled(40<value);
             btnlaser.setEnabled(50<value);
       }else{
             btnshoot.setEnabled(false);
             btnmissile.setEnabled(false);
             btnlaser.setEnabled(false);
       
       
       }
    }

    @Override
    public void AreaCleared(boolean slected) {
        if(slected){
            lblarea.setText("Area Cleared");
        }else{
            lblarea.setText("Area Not Cleared");
        }
        
        
     
        
      
        }

    @Override
    public void SendMainMessege(String messege) {
          textareaH.append(messege);
  
    }

    @Override
    public void DiliverMianMessege(String messege) {
        
    }

    public void setObserver(Obseverble obs) {
        this.obs = obs;
    }
    
   

}


