/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo.obs;


import Demo.Obseverble;
import static java.awt.SystemColor.text;

/**
 *
 * @author ASUS
 */
public class MainController extends javax.swing.JFrame implements Observer {
    private Obseverble obs;

    /**
     * Creates new form MainController
     */
    public MainController() {
        initComponents();
        this.setTitle("Main Controller");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblmessege = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollBar4 = new javax.swing.JScrollBar();
        jScrollBar3 = new javax.swing.JScrollBar();
        jScrollBar5 = new javax.swing.JScrollBar();
        jScrollBar6 = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        areacheckbox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        textarea1.setColumns(20);
        textarea1.setRows(5);
        jScrollPane1.setViewportView(textarea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 110));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 270, 110));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 260, 100));

        lblmessege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblmessegeActionPerformed(evt);
            }
        });
        jPanel1.add(lblmessege, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 30));

        btnsend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 30));

        jScrollBar1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 20, 110));

        jScrollBar2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.add(jScrollBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 20, 100));

        jScrollBar4.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.add(jScrollBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 20, 110));

        jScrollBar3.setBackground(new java.awt.Color(0, 102, 51));
        jScrollBar3.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(jScrollBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, 20));

        jScrollBar5.setBackground(new java.awt.Color(0, 102, 51));
        jScrollBar5.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(jScrollBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 280, 20));

        jScrollBar6.setBackground(new java.awt.Color(0, 102, 51));
        jScrollBar6.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(jScrollBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 290, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Fuel Count");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, 20));

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 40, 350));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ammo Count");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Soldier Count");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 120, 20));

        areacheckbox.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        areacheckbox.setText("Area Cleared");
        areacheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areacheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(areacheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 180, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton2.setText("Collect Informations");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));

        jLabel2.setText("Position");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
         /* if(messege!=null){
        String messege = lblmessege.;
        data.submitData("Helicopter : "+msg+".");}*/
      if(obs!=null){
        String messege = lblmessege.getText();
        obs.MainMessege("MainController : "+messege+"\n");}
       
    
    }//GEN-LAST:event_btnsendActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        obs.sendAll(jSlider1.getValue());        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void areacheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areacheckboxActionPerformed
       //obs.isSelected(rootPaneCheckingEnabled);
       if(areacheckbox.isSelected()){
            obs.isSelect(true);}
         else{
            obs.isSelect(false);}
       
       // TODO add your handling code here:
    }//GEN-LAST:event_areacheckboxActionPerformed

    private void lblmessegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblmessegeActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_lblmessegeActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController().setVisible(true);
            }
        });
    }
    
    public void setObseverble(Obseverble obs ){
        this.obs = obs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox areacheckbox;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollBar jScrollBar4;
    private javax.swing.JScrollBar jScrollBar5;
    private javax.swing.JScrollBar jScrollBar6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField lblmessege;
    private javax.swing.JTextArea textarea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateValue(int value) {
        
    }

    @Override
    public void AreaCleared(boolean selected) {
        
    }

    @Override
    public void SendMainMessege(String messege) {
        
    }

    @Override
    public void DiliverMianMessege(String data) {
        textarea1.append(data);
    }

   
   

    

}
