/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo.obs;

import Demo.Obseverble;
import Demo.obs.Observer;


/**
 *
 * @author ASUS
 */
public class Submarine extends javax.swing.JFrame implements Observer {

    private Obseverble obs;
   
    

    /**
     * Creates new form Submarine
     */
    public Submarine() {
        initComponents();
        setVisible(true);
        this.setTitle("Submarine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnmissile1 = new javax.swing.JButton();
        btnsonar = new javax.swing.JButton();
        btnmissile2 = new javax.swing.JButton();
        btnshoot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        positioncheck = new javax.swing.JCheckBox();
        lblarea = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaS = new javax.swing.JTextArea();
        textfield1 = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmissile1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmissile1.setText("Tomahawk Missile");
        jPanel1.add(btnmissile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));

        btnsonar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsonar.setText("Sonar Operation");
        jPanel1.add(btnsonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 30));

        btnmissile2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmissile2.setText("Trident-2 Missile");
        jPanel1.add(btnmissile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        btnshoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnshoot.setText("Shoot");
        jPanel1.add(btnshoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("Ammo Count");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Soldier Count");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 100, -1));

        positioncheck.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        positioncheck.setText("Position");
        jPanel1.add(positioncheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, -1));

        lblarea.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblarea.setText("Area Not Cleared");
        jPanel1.add(lblarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 50, -1));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("Oxigen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 60, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setText("Energy");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, -1));

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, 260));

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jPanel1.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 60, 260));

        textareaS.setColumns(20);
        textareaS.setRows(5);
        jScrollPane1.setViewportView(textareaS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 440, 140));
        jPanel1.add(textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, 30));

        btnsend.setBackground(new java.awt.Color(0, 102, 51));
        btnsend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsend.setForeground(new java.awt.Color(255, 255, 255));
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        if(obs!=null){
            String data = textfield1.getText();
            obs.DiliverMessege("Submarine : "+data+"\n");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnsendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmissile1;
    private javax.swing.JButton btnmissile2;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnshoot;
    private javax.swing.JButton btnsonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblarea;
    private javax.swing.JCheckBox positioncheck;
    public javax.swing.JTextArea textareaS;
    private javax.swing.JTextField textfield1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateValue(int value) {
       if(positioncheck.isSelected()==true){ 
        btnshoot.setEnabled(20<value);
        btnsonar.setEnabled(40<value);
        btnmissile1.setEnabled(50<value);
        btnmissile2.setEnabled(70<value);
        }else{
            btnshoot.setEnabled(false);
            btnsonar.setEnabled(false);
            btnmissile1.setEnabled(false);
            btnmissile2.setEnabled(false);
       
       
       }
    }
     public void AreaCleared(boolean slected) {
        if(slected){
            lblarea.setText("Area Cleared");
        }else{
            lblarea.setText("Area Not Cleared");
        }
    }
      public void SendMainMessege(String messege) {
          textareaS.append(messege);
  
    }

    @Override
    public void DiliverMianMessege(String messege) {
        
    }

    public void setObserver(Obseverble obs) {
         this.obs = obs;
    }
    
   
}
